//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS_Phase2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        public string BillNo { get; set; }
        public string PatientId { get; set; }
        public string DoctorId { get; set; }
        public Nullable<decimal> DoctorFees { get; set; }
        public Nullable<decimal> RoomCharges { get; set; }
        public Nullable<int> TotalDays { get; set; }
        public Nullable<decimal> OperationCharges { get; set; }
        public Nullable<decimal> MedicineFees { get; set; }
        public Nullable<decimal> LabFees { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual doctor doctor { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
