//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HMS_Phase2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treatment
    {
        public int TreatmentId { get; set; }
        public string PatientId { get; set; }
        public string LabId { get; set; }
        public string RoomNo { get; set; }
        public Nullable<System.DateTime> AdmissionDate { get; set; }
        public Nullable<System.DateTime> DischargeDate { get; set; }
        public Nullable<decimal> AmountPerDay { get; set; }
        public Nullable<System.DateTime> TreatmentDate { get; set; }
    
        public virtual Lab Lab { get; set; }
        public virtual Patient Patient { get; set; }
    }
}
